### PR TITLE
prefer node.raw when printing literals

### LINKED ISSUE #54: BigInt should print as a BigInt
BigInts appear to be parsed correctly, but are printed back out as regular ints, which is incorrect.

```
cr.print(cr.x`12345678901234567890n`).code
// => '12345678901234567890'
```

### PR DESCRIPTION
**Pull request by Conduitry**
This closes #54, and also simplifies the code when printing `Literal` nodes, and also preserves the type of quotes used on string literals.

There are some instances where we can't depend on `node.raw` existing. One is when we manually create a node object and include it with `${ }` in an expression. The other I don't quite have a handle on, so there might be more bugs here, but this PR shouldn't introduce any new ones hopefully, since we fall back to using `node.value` is `node.raw` doesn't exist/is falsy.

### CODE REVIEW

File: test/samples/array-expressions/expected.js [hunk 1]
```diff
@@ -1,9 +1,9 @@
 a = [1, 2, 3];
 
 b = [
-	"the quick brown fox jumps over the lazy dog",
-	"the quick brown fox jumps over the lazy dog",
-	"the quick brown fox jumps over the lazy dog",
+	'the quick brown fox jumps over the lazy dog',
```
Comment (tanhauhau) [inline test/samples/array-expressions/expected.js:4]: the quotation change is because that `node.raw` itself is wrapped with single quotes rather than double quotes?

this might break all snapshot tests downstream right?

Comment (Conduitry) [reply test/samples/array-expressions/expected.js:4]: `node.raw` is whatever string was used in the original parsed source for the particular literal. So these are single quotes because they were single quotes in `input.js`. I think this seems mildly nicer than always using double quotes and `JSON.stringify()`. Yeah this would break a lot of downstream js snapshot tests, but I don't really see that as a big problem. This library doesn't make any semver guarantees about what equivalent strings it uses for what expressions, and the snapshot tests are expected to be brittle and are easy to update.

**Review by tanhauhau — APPROVED** [review]
